# When running reshape, figure out which fields belong in which table
# Lifted from schema/schema_zika.json
mapping  = { 'dbinfo' : ['pathogen'],
                    'strains' : ['strain_id', 'strain_name', 'strain_owner',
                                 'host_species', 'host_age', 'host_sex',
                                 'symptom_onset_date', 'symptoms',
                                 'pregnancy_status', 'pregnancy_week',
                                 'microcephaly_status', 'usvi_doh_patient_id'],
                    'samples' : ['sample_id', 'sample_name', 'sample_owner',
                                 'collection_date', 'country', 'division', 'subdivision',
                                 'gps', 'collecting_lab', 'passage', 'tissue', 'ct',
                                 'usvi_doh_sample_id', 'sample_strain_name'],
                    'sequences' : ['sequence_id', 'sequence_name',
                                   'sequence_sample_name', 'sequence_owner', 'locus',
                                   'sequence_type', 'sequencing_lab', 'sharing',
                                   'sequence_url', 'attribution', 'sequence'],
                    'attributions' : ['attribution_id', 'attribution_owner',
                                      'attribution_source', 'publication_status',
                                      'attribution_date', 'attribution_title',
                                      'attribution_journal', 'attribution_url',
                                      'authors', 'pubmed_id']}
